### ISSUE TITLE
Knockback_Dash

### ISSUE THREAD

**Issue by Epicnoob1004** [GDevelopApp/GDevelop-extensions#196] opened 2021-07-29 19:33 UTC
## Describe the extension
Allows the enemy's to knock back the player if hit. Platform movement mode only bounces the player if the player hits an enemy from the left or right. Top-down bounces in all directions when a player contacts an enemy from any side. The dash lets you dash in your current direction if you have been knocked back the dash will go in the direction you were knocked back in. You can't have both top down and platform dash/ knockback enabled at 1 time
## Checklist
- [X] Extension has a proper name and description.
- [X] Extension has tags (for example: "platform, brick, breakable").
- [X] All behaviors have a description.
- [X] All functions (actions, conditions, expressions) have descriptions and proper sentences.
- [ ] I've followed the best practices listed on http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices
- [X] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Example
[KnockBack_Dash.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6912041/KnockBack_Dash.zip)

## Extension file
[KnockBack_Dash_Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6912042/KnockBack_Dash_Extension.zip)

**Comment by Entr0py404** [comment] 2021-07-30 05:27
For checklist use - [x]
Description in behavior need to be shorter and match the wording of the object behavior descriptions.
Name displayed for behavior also should match capitalization.
![Screenshot 2021-07-29 220027](https://user-images.githubusercontent.com/75917656/127604230-d4af54de-b5c1-49ec-82b5-35807c08a3a8.png)

For your variables they should probably be object behavior properties or [follow the best practices for variables](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices#variables) 

Sentence in event needs to be a clear sentences for actions/conditions displayed in the events sheet.
![Screenshot 2021-07-29 222125](https://user-images.githubusercontent.com/75917656/127604501-641b9a28-70bf-4634-84f2-ad17e44497a6.png)

Not 100% sure if needed but are you cleaning up the tweening by deleting the tween when its no longer needed?
see "Warning: This instruction is crucial." message in page http://wiki.compilgames.net/doku.php/gdevelop5/behaviors/tween

**Comment by Epicnoob1004** [comment] 2021-07-30 05:52
Ok thank you. I will try to fix the stuff. the tween deletion is to stop a
bug. Where the player clips through the ground in platformer mode and helps
to optimize it a bit

**Comment by Entr0py404** [comment] 2021-07-30 06:00
Dashing in the wrong direction and dashing into a solid
![Oa82UTcrA9](https://user-images.githubusercontent.com/75917656/127607851-0569acd6-fcc9-40a1-9d69-e671f9399dcb.gif)

**Comment by Epicnoob1004** [comment] 2021-07-30 06:05
Ya u have to move before or else it will go in the direction u where in
previously  a bit if u try to dash through a solid it dose that idk how to
fix it maybe i can get the current direction and move the player untill it
is not touching a platform ?  Also u notice any problems with the knockback
part ?

**Comment by Epicnoob1004** [comment] 2021-07-30 18:39
@Entr0py404  i am almost done with the fixes   once i am done  i will update this

**Comment by Epicnoob1004** [comment] 2021-08-01 02:14
@Entr0py404  everything should be fixed now  had a few set backs mainly my gdevlop freezing and crashing  for some reason but it should be good to go

**Comment by Entr0py404** [comment] 2021-08-01 11:35
Hey looks like you closed this did you mean to ?

**Comment by Epicnoob1004** [comment] 2021-08-01 18:27
@Entr0py404  i miss click lol sorry

**Comment by Epicnoob1004** [comment] 2021-08-01 18:28
is it good?

**Comment by Epicnoob1004** [comment] 2021-08-01 19:45
No misclick dose everything look good?  Just updated everything

**Comment by Epicnoob1004** [comment] 2021-08-03 18:57
can i close it?

**Comment by Epicnoob1004** [comment] 2021-08-06 16:05
i updated everything.      hopefully u all can see this

**Comment by Epicnoob1004** [comment] 2021-08-06 16:07
###  **extension**  
[KnockBack_Dash_Extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6946698/KnockBack_Dash_Extension.zip)
### **example project** 
[KnockBack_Dash.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6946702/KnockBack_Dash.zip)


this is the update

**Comment by Bouh** [comment] 2021-08-07 12:39
Thanks for this new extension.
Can you read the best practice guide please, the sentences have not the right format. the labels too.
There is no caps on the first word. There is no type of unit on fields, like on **x to move** input.
Long description can be added on inputs for add a longer description if needed.
There is a lot of unnecessary and repetitive events & conditions/actions.

**Comment by Epicnoob1004** [comment] 2021-08-07 14:53
Ok

**Comment by Bouh** [comment] 2021-09-30 19:32
Are the changes expected soon? If not, and if no one picks up I'll close the topic and tag the extension as abandoned this Monday.

**Comment by Bouh** [comment] 2021-09-30 19:34
@arthuro555 that was an expected behaviour from the bot?

**Comment by arthuro555** [comment] 2021-09-30 19:34
Whoops, labelling an issue will trigger the automation of the tag New Extension is present after the tag modification

**Comment by Epicnoob1004** [comment] 2021-09-30 20:10
This extension is not abandoned i am working on optimizing it its going to be a while but definitely still going

**Comment by Bouh** [comment] 2021-09-30 20:20
> This extension is not abandoned i am working on optimizing it its going to be a while but definitely still going

Nice to heard you :)
Keep us inform when you have more!

**Comment by Epicnoob1004** [comment] 2021-09-30 20:42
Ok will do

**Comment by Bouh** [comment] 2022-01-23 17:10
We are closing this thread.
You can continue to discuss here and we will reopen the thread when an update to the extension is available.

**Closed by Bouh** 2022-01-23 17:10 UTC
Labels: ✨ New extension, help wanted

**Comment by Epicnoob1004** [comment] 2022-01-25 03:35
Ok
