### ISSUE TITLE
Sprite Button Maker

### ISSUE THREAD

**Issue by GameDevPassion** [GDevelopApp/GDevelop-extensions#539] opened 2022-08-18 00:19 UTC
### Description

This extension changes your sprites depending on weather you hover over them or press them.
Easy event conditions: find out weather a sprite is clicked or being pressed.

The extension is fully customizable!
Define how much the button moves when clicked, weather it changes animation when clicked, if it responds only to Left mouse clicks or other Mouse clicks etc. ...
And you can change all settings inside the event sheet!

Features include:

-Super easy and intuitive: install the behavior and you already have a usable button!
-Setting draggable clicks on/off
-setting hover/pressed animations
-setting how much the button moves up/down when hovering/pressing
-deactivate all button events
-deactivate button animations while the button keeps responding to clicks

### How to use the extension

You install the behavior on a sprite, and you can immediately set the parameters.

You can change all parameters inside the event sheet as well.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[sampleproject.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9366725/sampleproject.zip)

### Extension file

[extension.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9366726/extension.zip)

**Comment by arthuro555** [comment] 2023-09-26 14:57
Closing as duplicate of #540

**Closed by arthuro555** 2023-09-26 14:57 UTC
Labels: ✨ New extension
