### ISSUE TITLE
Flash and transition painter

### ISSUE THREAD

**Issue by westboy31** [GDevelopApp/GDevelop-extensions#84] opened 2020-12-19 09:40 UTC
## Describtion :
(this extension has nothing to do with the existing flash extension which make objects blink)
this extension is a behavior for shape painter object, allows you to paint a color all over the screen for period of time with different effect (useful for simulate flash and transition effect).

* Paint effect : Action to paint a color all over the screen for a period of time with specific effect.
the effect type is indicated with these strings as arguments :
    * __Flash:__ is a monochrome color appear with fade then disappear with fade out.
    * __Vertical :__ is a monochrome color comes from right side then comes back.
    * __Horizontal :__ is a monochrome color come from top side then comes back.
    * __Circular:__ is a circle which increases from the center and narrows.
* Paint effect ended: event when the paint effect ends.

## Checklist

- [x] Extension has a proper name and description.
- [x] Extension has tags (for example: "platform, brick, breakable").
- [x] All behaviors have a description.
- [x] All functions (actions, conditions, expressions) have descriptions.
- [x] I confirm that this extension can be intergrated to this GitHub repository, distributed and MIT licensed.

## Game file exemple :
[Game.zip](https://github.com/4ian/GDevelop-extensions/files/5719151/Game.zip)

## Extension file :
[Extension.zip](https://github.com/4ian/GDevelop-extensions/files/5719142/Extension.zip)

## Screenshot : 
![uxQiYAGjs4](https://user-images.githubusercontent.com/49737293/102685976-b7630180-41e4-11eb-89bf-20218ff401a1.gif)

**Comment by tristanbob** [comment] 2020-12-21 19:53
This is brilliant!  I was trying to come up with ways to provide good scene transitions, but I didn't think about using a shape painter object.  Now I think it is the perfect thing for the job; it's dynamic, configurable, and doesn't require an existing object.

I love what you have done so far, especially the "Damage Here" effect. 

I want to think about other possible uses for this extension to see if there are more options I would want as a user.

**Comment by westboy31** [comment] 2020-12-21 20:24
> This is brilliant! I was trying to come up with ways to provide good scene transitions, but I didn't think about using a shape painter object. Now I think it is the perfect thing for the job; it's dynamic, configurable, and doesn't require an existing object.
> 
> I love what you have done so far, especially the "Damage Here" effect.
> 
> I want to think about other possible uses for this extension to see if there are more options I would want as a user.

thank you , what could be good is if community could bring more differents effects i just make very basic painting shapes , i mean something like we can find in video editing software

**Comment by 4ian** [comment] 2020-12-21 20:27
That's a nice idea to use the shape painter for such transitions :) I think we should name this extension "Transition Painter" maybe?

**Comment by westboy31** [comment] 2020-12-21 20:41
> That's a nice idea to use the shape painter for such transitions :) I think we should name this extension "Transition Painter" maybe?

As you want , to be sincere i wasn't inspired by the name , i took first thing on my mind

**Comment by GustavoMarciano** [comment] 2021-01-11 18:25
I don't know if it's a bug, but the effects of one object are affecting the others, for example I created two shape painters with painter transition extension and condition 
"When the X painting effect ends" 
Effects all objects with the TransitionPainter

**Comment by 4ian** [comment] 2021-01-11 18:26
Probably scene variables that should be moved to object variables?

**Comment by GustavoMarciano** [comment] 2021-01-11 18:29
for better exemplification
![Capturar](https://user-images.githubusercontent.com/23220658/104222944-c32b9780-5421-11eb-8db9-ad1cf52f3935.PNG)

![MKOFF23](https://user-images.githubusercontent.com/23220658/104223011-d76f9480-5421-11eb-8c3d-1f695bdb5616.gif)

**Comment by GustavoMarciano** [comment] 2021-01-11 18:39
> Probably scene variables that should be moved to object variables?

it doesn't seem to be something related to a global variable, I have no idea for me the existing code seems ok

![Capturar01](https://user-images.githubusercontent.com/23220658/104223854-f3276a80-5422-11eb-839e-852c9e3419d7.PNG)

**Comment by westboy31** [comment] 2021-01-12 13:53
I thought about it, and I don't know the causes, they are not scene variables because there is no scene variable, maybe you are drawing your button with the same painter, in this case that explains everything, otherwise it could be a layer or a camera issue, as the plugin uses the default camera and painter's layer, hope this helped you.

**Comment by GustavoMarciano** [comment] 2021-01-12 15:09
ok I did a test on a new project, and those were the results
![Capturar](https://user-images.githubusercontent.com/23220658/104332530-098b0000-54cf-11eb-82a4-05df871abaa4.PNG)
![Capturar1](https://user-images.githubusercontent.com/23220658/104332550-0d1e8700-54cf-11eb-9a85-78bafa3578ea.PNG)
![M2](https://user-images.githubusercontent.com/23220658/104332568-13146800-54cf-11eb-8375-eccf79b1c969.gif)

**Comment by GustavoMarciano** [comment] 2021-01-12 15:25
testing on a new project and those were the results
![Capturar1](https://user-images.githubusercontent.com/23220658/104334487-304a3600-54d1-11eb-8168-2d16a7d72068.PNG)
![Capturar](https://user-images.githubusercontent.com/23220658/104334489-317b6300-54d1-11eb-974f-38275bf82235.PNG)
![M2](https://user-images.githubusercontent.com/23220658/104334494-33452680-54d1-11eb-8e7d-7291983b2cbb.gif)

**Comment by GustavoMarciano** [comment] 2021-01-12 15:49
@westboy31  
I removed the paint action and look what is happening, maybe the behavior without a set timer is conflicting with the paint effect ended action

![Capturar3](https://user-images.githubusercontent.com/23220658/104337126-e7e04780-54d3-11eb-92b2-51bc0696ea19.PNG)
![M3](https://user-images.githubusercontent.com/23220658/104337129-e9117480-54d3-11eb-9a43-5b100c0af0e6.gif)

**Comment by westboy31** [comment] 2021-01-12 20:38
First @GustavoMarciano :
very nice your example really helped me to fix the problem ; 
I'm not sure the reason, but I think when you check a timer, in our case the timer of "when the paint effect ends", it automatically initializes and starts the timer, i paused the timer when creating the object and deactivated the pause when starting the behavior.
![UabxURyiow](https://user-images.githubusercontent.com/49737293/104369696-26025900-551e-11eb-9c93-2ce84ef26c9b.png)
![frrwbC7r6n](https://user-images.githubusercontent.com/49737293/104369724-30bcee00-551e-11eb-8d51-689f7e260db8.png)


than : 
I added an enhancement to the condition that detects the end of the effect, the problem was that the condition became true a little after the effect ended, I increased the value of the effect with a few milliseconds (3Delta) and decreased the same value for the condition which detects the end, so the painting effect becomes longer but the condition which detects its end is more precise, and in addition to this we have a better transition .
![5kc1wmzqq2](https://user-images.githubusercontent.com/49737293/104369816-51854380-551e-11eb-9b5f-65806c3d57ee.png)
![EuRbBHmUKA](https://user-images.githubusercontent.com/49737293/104369781-46caae80-551e-11eb-8ed6-a3d747875d68.png)

the game exemple of @GustavoMarciano with correction : 
[gameExemple2.zip](https://github.com/4ian/GDevelop-extensions/files/5804560/gameExemple2.zip)

the extension with correction :
[Extension2.zip](https://github.com/4ian/GDevelop-extensions/files/5804567/Extension2.zip)

**Comment by arthuro555** [comment] 2021-04-20 15:47
I reworded the extensions for better consistency and prefixed the variables as described in the best practices: [https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/5fe0e6f737cef020a42b50ba/2e9b53e7a80d374e2603bac217428c4e/Transitions.json](Extension.json).

I also think I found a bug, not sure if my modifications are the cause though: If I go in damage then on flash with the initial example and the updated extension, the flash finishes too early.

**Comment by Midhil457** [comment] 2021-07-13 11:49
> I reworded the extensions for better consistency and prefixed the variables as described in the best practices: https://trello-attachments.s3.amazonaws.com/5fd532f01e99c97130e99fe9/5fe0e6f737cef020a42b50ba/2e9b53e7a80d374e2603bac217428c4e/Transitions.json.

The link you provided isn't working now. Could you upload it again?

:)

**Comment by Midhil457** [comment] 2021-07-16 14:21
Hi, I wasn't able to go through the whole extension, and only got the time to see some parts

The parameter that asks for the transition type (circular, vertical, horizontal, etc..) can be a option parameter for easier use. Also for the direction (it can be forward, backwards, both). Also, the parameter labels can be better("duration" instead of "How long time the color keep on screen.", ''End Opacity" instead of "The maximum of the opacity only for flash."). Also, I don't think full stops are needed in the parameter labels

:)

**Comment by westboy31** [comment] 2021-07-16 18:14
@arthuro555  you were right, the event that detects the end was wrong for the forward and the backward, I added
a condition, it works now.
I have taken into consideration @Midhil457  remarks and send you the extention and the game with corrections.
Just for "End Opacity", I kept "(only for flash )" because the opacity does not change with the other transitions.
This extension was done 9 months ago, I think at that time the option parameters were not available.

[game + extention.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/6832628/game.%2B.extention.zip)

**Comment by arthuro555** [comment] 2021-07-16 20:49
Here is my quick review:

- The extension is not following the [best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices). Please ensure that they are followed.
- Try to make the comments more readable (no space between last word and dots, capitalize, write full sentences...)

Those are just details to keep the extension maintainable, otherwise everything looks good to me!

**Comment by arthuro555** [comment] 2021-08-18 14:54
It's been a month without updates, I am assuming the extension has been abandoned. If the original poster does not come back or no one takes over finishing this extension, the submission will be closed in 10 days.

**Comment by westboy31** [comment] 2021-08-18 15:48
It must be a misunderstanding, i thought the extension was ready to be pulled, and really I don't know what to change in the extension to follow best practices.

**Comment by arthuro555** [comment] 2021-08-18 15:51
Ah, I see, sorry for the confusion. I recommend you go through the best practices and check for each point if your extension is complying. From what I remember, at least semantic versioning + variable and timer naming conventions are not respected.

**Comment by westboy31** [comment] 2021-08-18 21:36
I think it's done, I made some corrections to the comments, and rename the variables and timers, from what I read they must contain specific prefixes.
[TransitionPainter.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/7010260/TransitionPainter.zip)

**Comment by arthuro555** [comment] 2021-08-19 20:28
LGTM!

**Comment by arthuro555** [comment] 2021-08-19 20:43
Thanks for your contribution 🥳

**Closed** 2021-08-19 20:42 UTC
Labels: ✨ New extension, 🏁 Extension almost ready: final fixes
