### ISSUE TITLE
Sprite ButtonsNew extension: <title>

### ISSUE THREAD

**Issue by GameDevPassion** [GDevelopApp/GDevelop-extensions#538] opened 2022-08-17 19:19 UTC
### Description

Changes your sprites depending on weather you hover over them or press them.
Easy even condition: find out weather a sprite is clicked or being pressed.

The extension is fully customizable!
Define how much the button moves when clicked, weather it changes animation when clicked, if it responds only to Left mouse clicks or other Mouse clicks etc. ...

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[Sprite Button Sample Project.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9365537/Sprite.Button.Sample.Project.zip)

### Extension file

[Sprite_Buttons.zip](https://github.com/GDevelopApp/GDevelop-extensions/files/9365538/Sprite_Buttons.zip)

**Comment by arthuro555** [comment] 2023-09-26 14:57
Closing as duplicate of #540

**Closed by arthuro555** 2023-09-26 14:57 UTC
Labels: ✨ New extension
